# fill and move to secrets.yaml
wifi_ssid: ""
wifi_password: ""
wifi_bssid: ""
wifi_static_ip: ""
wifi_gateway: ""
wifi_subnet: ""
wifi_dns1: ""
wifi_dns2: ""
api_key: ""
ota_password: ""

# oebb-monitor endpoint + station configuration
departures_host: "" # protocol and host and where the monitor service is reachable e.g. http://pi.local:5010
departures_stations: "" # e.g. , separated list of departure ids with optionally : separated destination station ids
